name: react-native-android-build-apk
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build IOS
    runs-on: macos-latest

steps:
  - name: Checkout repository
        uses: actions/checkout@v2

  - name: Install dependencies
        run: npm install

  - name: Build and export iOS
        uses: yukiarrr/ios-build-action@v1.4.0
        with:
          project-path: ${{ github.workspace }}/ios/TypeScriptDemo.xcodeproj
          workspace-path: ${{ github.workspace }}/ios/TypeScriptDemo.xcworkspace
          scheme: TypeScriptDemo
          export-method: ad-hoc
          configuration: Release
          output-path: artifacts/output.ipa
          p12-base64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          certificate-password: ${{ secrets.P12_PASSWORD }}
          mobileprovision-base64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          code-signing-identity: ${{ secrets.KEYCHAIN_PASSWORD }}
          team-id: ${{ secrets.TEAM_ID }}
