name: Build Android & iOS

# Triggered when code is pushed to any branch in a repository
on: push
# on:
#   push:
#     branches:
#       - 'master'

jobs:
  runs-on: macos-latest
  steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/Library/Caches/CocoaPods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
    - uses: actions/cache@v2
      with:
        path: ~/.cocoapods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
    - run:
        name: Install Dependencies
        command: npm install
    - run:
        name: Check Linter
        command: npm run linter
  # steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/cache@v2
  #     with:
  #       path: node_modules
  #       key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
  #       restore-keys: |
  #         ${{ runner.os }}-yarn-
  #   - uses: actions/cache@v2
  #     with:
  #       path: ~/Library/Caches/CocoaPods
  #       key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
  #       restore-keys: |
  #         ${{ runner.os }}-pods-
  #   - uses: actions/cache@v2
  #     with:
  #       path: ~/.cocoapods
  #       key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
  #       restore-keys: |
  #         ${{ runner.os }}-pods-

  #   - run: npm install --frozen-lockfile

  #   - run: pod install
  #     working-directory: ios

  #   - run: xcodebuild clean archive -workspace testCiCdReactNative.xcworkspace -scheme testCiCdReactNative -archivePath testCiCdReactNative.xcarchive CODE_SIGNING_ALLOWED=NO | xcpretty
  #     working-directory: ios
