name: Pull Request into Master, Develop and Preprod

on:
  pull_request:
    branches:
      - 'master'

jobs:
  #First job
  install-and-test:
    runs-on: iMac (21.5-inch, 2017)

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: v14.20.1
          cache: 'npm'

      - name: Install Node modules
        run: npm i

      - name: Linting
        run: npm linter
