name: react-native-android-build-apk
on:
  push:
    branches:
      - master
jobs:
  install-and-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install npm dependencies
        run: |
          npm install
      - name: Run Lint
        run: |
          npm run linter
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for Gradle
        run: cd android && chmod +x ./gradlew

      - name: Build with Gradles
        run: cd android && ./gradlew assembleDebug

      - name: Upload APK TestApp.io
        uses: testappio/github-action@v5
        with:
          api_token: ${{secrets.DEMO_APP_IO_API_TOKEN}}
          app_id: ${{secrets.DEMO_APP_IO_APP_ID}}
          file: app/build/outputs/apk/debug/app-debug.apk
          release_notes: 'test release'
          git_release_notes: true
          include_git_commit_id: false
          notify: true

      # - name: Clean Android
      #   run: |
      #   cd android && ./gradlew clean
      # - name: Build Android
      #   run: |
      #   cd android && ./gradlew bundleRelease
    # - name: Upload Artifact
    #   uses: actions/upload-artifact@v1
    #   with:
    #     name: app-release.apk
    #     path: android/app/build/outputs/apk/release/
