name: react-native-android-build-apk
on:
  push:
    branches:
      - master
jobs:
  # Android-Release:
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Install npm dependencies
  #       run: |
  #         npm install
  #     - name: Run Lint
  #       run: |
  #         npm run linter
  #     - name: Cache Gradle
  #       uses: actions/cache@v2
  #       with:
  #         path: ~/.gradle/caches
  #         key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
  #     - name: Set up JDK
  #       uses: actions/setup-java@v2
  #       with:
  #         java-version: '11'
  #         distribution: 'adopt'
      
  #     # - name: Cache Gradle Dependencies
  #     #   uses: actions/cache@v2
  #     #   with:
  #     #     path: ~/.gradle/caches
  #     #     key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
  #     #     restore-keys: |
  #     #       ${{ runner.os }}-gradle-

  #     - name: Grant execute permission for Gradle
  #       run: cd android && chmod +x ./gradlew

  #     - name: Gradle Clean
  #       run: cd android && ./gradlew clean

  #     - name: Build with Gradles
  #       run: cd android && ./gradlew assembleRelease

  #     - name: Upload APK TestApp.io
  #       uses: testappio/github-action@v5
  #       with:
  #         api_token: ${{secrets.DEMO_APP_IO_API_TOKEN}}
  #         app_id: ${{secrets.DEMO_APP_IO_APP_ID}}
  #         file: android/app/build/outputs/apk/release/app-release.apk
  #         release_notes: 'test release'
  #         git_release_notes: true
  #         include_git_commit_id: false
  #         notify: true

  #Done Change certificate

  IOS_RELEASE:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and export iOS
        uses: yukiarrr/ios-build-action@v1.4.0
        with:
          project-path: ios/TypeScriptDemo.xcodeproj
          workspace-path: ios/TypeScriptDemo.xcworkspace
          scheme: TypeScriptDemo
          export-method: ad-hoc
          configuration: Release
          output-path: artifacts/output.ipa
          p12-base64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          certificate-password: ${{ secrets.P12_PASSWORD }}
          mobileprovision-base64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          code-signing-identity: ${{ secrets.KEYCHAIN_PASSWORD }}
          team-id: ${{ secrets.TEAM_ID }}


