name: react-native-android-build-apk
on:
  push:
    branches:
      - master
jobs:
  install-and-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install npm dependencies
        run: |
          npm install
      - name: Run Lint
        run: |
          npm run linter
  build-android:
    needs: install-and-test
    uses: ./.github/workflows/android-build.yml
    with:
      environment: release
    secrets: inherit
